name: Build and Deploy
on:
  push:
    branches: main
  pull_request:
    branches: main

env:
  REGEX_INCLUDE: "\\.(pdf|link|txt)$"

jobs:
  build:
    name: Build pdfs out of tex,md and various doc files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Install tex
        run: |
          sudo apt update
          sudo apt install texlive-latex-extra texlive-lang-italian texlive-lang-english texlive-fonts-recommended texlive-bibtex-extra texlive-science latexmk

      - name: Install format conversion tools
        run: |
          sudo apt install libreoffice
          wget https://github.com/jgm/pandoc/releases/download/2.18/pandoc-2.18-linux-amd64.tar.gz -O /tmp/pandoc.tar.gz
          tar xfz /tmp/pandoc.tar.gz -C /tmp
          sudo mv /tmp/pandoc-*/bin/* /usr/bin

      - name: Recursively compile tex files
        run: ./.github/workflows/rec "*\.tex$" "latexmk -pdf"

      - name: Recursively compile (doc|ppt)x? files
        run: ./.github/workflows/rec "*\.(doc|ppt)x?$" "libreoffice --headless --convert-to pdf --outdir ."

      - name: Recursively compile md files
        run: ./.github/workflows/rec "*\.md$" ${GITHUB_WORKSPACE}/.github/workflows/md2pdf

      - name: Generate build artifact
        uses: actions/upload-artifact@v2
        with:
          name: build-result
          path: .

  statik:
    name: Generate the static listing
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download compiled files
        uses: actions/download-artifact@v2
        with:
          name: build-result

      - name: Install go
        uses: actions/setup-go@v3
        with:
          go-version: ">=1.18.0"

      - name: Install statik
        run: go install github.com/lucat1/statik@latest

      - name: Update packages and install rsync
        run: sudo apt install rsync

      - name: Generate static directory listing
        run: $(go env GOPATH)/bin/statik -header .github/workflows/header.gohtml -l -b "https://${{ github.event.repository.owner.name }}.github.io/${{ github.event.repository.name }}/" -i "$REGEX_INCLUDE"

      - name: Generate site artifact
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v2
        with:
          name: statik-build
          path: ./site

  deploy:
    name: Deploy to Github Pages
    runs-on: ubuntu-latest
    needs: statik
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Download static site artifact
        uses: actions/download-artifact@v2
        with:
          name: statik-build
          path: site

      - uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages
          folder: site
